# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 676f88dfa75f178d2b364c17c1c236975c2a28205984f867bd73fdc08c9bd3eb74c86d18d38245d1e62d8a02a4e54c6711aef3ba256cce767472a3db911e5b9a

test:
  secret_key_base: 84cf36f0e2a172505a50d3711644cb46ea9bf78fd14d50a822de3b520c8be0499833952765ba45ee321e2851c57eb0930b12ae14ad1f50bcc340dfb772f96637

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
